### ISSUE TITLE
Error: Could not load server certificate!

### ISSUE THREAD

**Issue by jstjst** [o3ma/o3demo#2]
After starting the demo I get the error `Could not load server certificate!`
I have no idea what's going wrong

**Comment by corrupt** [comment]
That's the one part of documentation I'll add right now. You have to copy cert.pem from the library to the directory of your program. It is used to validate self-signed Threema's server certificate.

**Comment by corrupt** [comment]
Sorry, I accidentally closed this one. Please let me know if you get things working.

**Comment by corrupt** [comment]
I modified our unirest fork to remove this problem entirely now. If you pull o3ma/unirest-go again, this shouldn't be a problem anymore. Please confirm.

**Comment by jstjst** [comment]
Thanks for the fast response.
Tested only the second solution, works fine for me.
